---
resources:
  - name: simple-packaging
    type: git
    source:
      uri: https://github.com/devinchristianson/simple-packaging.git
      branch: main

jobs:
  - name: build-packages
    plan:
      - get: simple-packaging
        trigger: true
      - in_parallel:
        - across:
          - var: pkg-type
            values: ["pacman", "rpm", "deb"]
          task: build-((.:pkg-type))-hello
          input_mapping: 
            source: simple-packaging/packages/hello
          file: simple-packaging/packages/hello/task.yml
