groups:
  - jobs:
      - package-*-hello-world
    name: hello-world
  - jobs:
      - package-*-yq
    name: yq
jobs:
  - name: package-pacman-hello-world
    plan:
      - in_parallel:
          - get: simple-packaging
            trigger: true
          - get: index
            params:
              options:
                - --exclude '*'
                - --include 'mdicsme.db'
                - --include 'mdicsme.files'
                - --include 'mdicsme.*.tar.gz'
                - --include 'mdicsme.*.tar.gz.sig'
              prefix: pacman
          - get: devinchristianson-fpm_archlinux-latest
      - config:
          image_resource:
            name: alpine
            source:
              repository: alpine
            type: registry-image
          inputs:
            - name: simple-packaging
          outputs:
            - name: version
          platform: linux
          run:
            args:
              - -exc
              - echo 0.1.0 > version/version
            path: sh
        task: save-version
      - config:
          inputs:
            - name: simple-packaging
            - name: version
          outputs:
            - name: packaged
          platform: linux
          run:
            args:
              - -exc
              - fpm -t pacman -s dir --name hello-world --version $(cat version/version) --architecture native --description 'Simple hello world program' --license 'MIT' --url 'https://github.com/devinchristianson/simple-packaging' --vendor 'Built by github.com/devinchristianson/simple-packaging' -p packaged/ --depends bash simple-packaging/packages/hello-world/pkg/hello=/usr/bin/hello-world
            path: sh
        image: devinchristianson-fpm_archlinux-latest
        task: package-pacman-hello-world
      - config:
          inputs:
            - name: packaged
            - name: version
          outputs:
            - name: packaged
          params:
            GPG_KEY_ID: ((gpg.key-id))
            GPG_PRIVATE_KEY: ((gpg.private-key))
          platform: linux
          run:
            args:
              - -exc
              - /gpg-init.sh gpg --use-agent --output packaged/hello-world-$(cat version/version)-1-x86_64.pkg.tar.zst.sig --detach-sig packaged/hello-world-$(cat version/version)-1-x86_64.pkg.tar.zst
            path: sh
        image: devinchristianson-fpm_archlinux-latest
        task: sign-pacman-hello-world
      - in_parallel:
          - params:
              file: packaged/hello-world-*-x86_64.pkg.tar.zst
            put: pacman-pkg-hello-world
          - params:
              file: packaged/hello-world-*-x86_64.pkg.tar.zst.sig
            put: pacman-pkg-hello-world-sig
          - do:
              - config:
                  inputs:
                    - name: packaged
                    - name: version
                    - name: index
                  outputs:
                    - name: index
                  params:
                    GPG_KEY_ID: ((gpg.key-id))
                    GPG_PRIVATE_KEY: ((gpg.private-key))
                  platform: linux
                  run:
                    args:
                      - -exc
                      - /gpg-init.sh repo-add --verify --sign -n index/mdicsme.db.tar.gz packaged/hello-world-$(cat version/version)-1-x86_64.pkg.tar.zst
                    path: sh
                image: devinchristianson-fpm_archlinux-latest
                task: rebuild-index-for-pacman-hello-world
              - get_params:
                  options:
                    - --exclude '*'
                    - --include 'mdicsme.db'
                    - --include 'mdicsme.files'
                    - --include 'mdicsme.*.tar.gz'
                    - --include 'mdicsme.*.tar.gz.sig'
                  prefix: pacman
                  source_dir: index
                params:
                  options:
                    - --exclude '*'
                    - --include 'mdicsme.db'
                    - --include 'mdicsme.files'
                    - --include 'mdicsme.*.tar.gz'
                    - --include 'mdicsme.*.tar.gz.sig'
                  prefix: pacman
                  source_dir: index
                put: index
    serial_groups:
      - pacman
  - name: package-rpm-hello-world
    plan:
      - in_parallel:
          - get: simple-packaging
            trigger: true
          - get: index
            params:
              options:
                - --exclude '*'
                - --include 'repodata/*'
                - --include 'cache/*'
              prefix: rpm
          - get: devinchristianson-fpm_fedora-37
      - config:
          image_resource:
            name: alpine
            source:
              repository: alpine
            type: registry-image
          inputs:
            - name: simple-packaging
          outputs:
            - name: version
          platform: linux
          run:
            args:
              - -exc
              - echo 0.1.0 > version/version
            path: sh
        task: save-version
      - config:
          inputs:
            - name: simple-packaging
            - name: version
          outputs:
            - name: packaged
          platform: linux
          run:
            args:
              - -exc
              - fpm -t rpm -s dir --name hello-world --version $(cat version/version) --architecture native --description 'Simple hello world program' --license 'MIT' --url 'https://github.com/devinchristianson/simple-packaging' --vendor 'Built by github.com/devinchristianson/simple-packaging' -p packaged/ --depends bash simple-packaging/packages/hello-world/pkg/hello=/usr/bin/hello-world
            path: sh
        image: devinchristianson-fpm_fedora-37
        task: package-rpm-hello-world
      - config:
          inputs:
            - name: packaged
            - name: version
          outputs:
            - name: packaged
          params:
            GPG_KEY_ID: ((gpg.key-id))
            GPG_PRIVATE_KEY: ((gpg.private-key))
          platform: linux
          run:
            args:
              - -exc
              - /gpg-init.sh rpm --addsign packaged/hello-world-$(cat version/version)-1.x86_64.rpm
            path: sh
        image: devinchristianson-fpm_fedora-37
        task: sign-rpm-hello-world
      - in_parallel:
          - params:
              file: packaged/hello-world-*.x86_64.rpm
            put: rpm-pkg-hello-world
          - do:
              - config:
                  inputs:
                    - name: packaged
                    - name: version
                    - name: index
                  outputs:
                    - name: index
                  platform: linux
                  run:
                    args:
                      - --update
                      - --cachedir
                      - cache
                      - -o
                      - index
                      - packaged
                    path: createrepo
                image: devinchristianson-fpm_fedora-37
                task: rebuild-index-for-rpm-hello-world
              - config:
                  inputs:
                    - name: packaged
                    - name: version
                    - name: index
                  outputs:
                    - name: index
                  params:
                    GPG_KEY_ID: ((gpg.key-id))
                    GPG_PRIVATE_KEY: ((gpg.private-key))
                  platform: linux
                  run:
                    args:
                      - gpg
                      - --yes
                      - --detach-sign
                      - --armor
                      - index/repodata/repomd.xml
                    path: /gpg-init.sh
                image: devinchristianson-fpm_fedora-37
                task: resign-index-for-rpm-hello-world
              - get_params:
                  options:
                    - --exclude '*'
                    - --include 'repodata/*'
                    - --include 'cache/*'
                  prefix: rpm
                  source_dir: index
                params:
                  options:
                    - --exclude '*'
                    - --include 'repodata/*'
                    - --include 'cache/*'
                  prefix: rpm
                  source_dir: index
                put: index
    serial_groups:
      - rpm
  - name: package-pacman-yq
    plan:
      - in_parallel:
          - get: yq-release
            params:
              globs:
                - yq_linux_amd64
            trigger: true
          - get: index
            params:
              options:
                - --exclude '*'
                - --include 'mdicsme.db'
                - --include 'mdicsme.files'
                - --include 'mdicsme.*.tar.gz'
                - --include 'mdicsme.*.tar.gz.sig'
              prefix: pacman
          - get: devinchristianson-fpm_archlinux-latest
      - config:
          image_resource:
            name: alpine
            source:
              repository: alpine
            type: registry-image
          inputs:
            - name: yq-release
          outputs:
            - name: version
          platform: linux
          run:
            args:
              - -exc
              - echo $(cat yq-release/tag) > version/version
            path: sh
        task: save-version
      - config:
          inputs:
            - name: yq-release
            - name: version
          outputs:
            - name: packaged
          platform: linux
          run:
            args:
              - -exc
              - fpm -t pacman -s dir --name yq --version $(cat version/version) --architecture native --description 'yq is a portable command-line YAML, JSON, XML, CSV and properties processor' --license 'Apache 2.0' --url 'https://github.com/mikefarah/yq' --vendor 'Built by github.com/devinchristianson/simple-packaging' -p packaged/ yq-release/yq_linux_amd64=/usr/bin/yq
            path: sh
        image: devinchristianson-fpm_archlinux-latest
        task: package-pacman-yq
      - config:
          inputs:
            - name: packaged
            - name: version
          outputs:
            - name: packaged
          params:
            GPG_KEY_ID: ((gpg.key-id))
            GPG_PRIVATE_KEY: ((gpg.private-key))
          platform: linux
          run:
            args:
              - -exc
              - /gpg-init.sh gpg --use-agent --output packaged/yq-$(cat version/version)-1-x86_64.pkg.tar.zst.sig --detach-sig packaged/yq-$(cat version/version)-1-x86_64.pkg.tar.zst
            path: sh
        image: devinchristianson-fpm_archlinux-latest
        task: sign-pacman-yq
      - in_parallel:
          - params:
              file: packaged/yq-*-x86_64.pkg.tar.zst
            put: pacman-pkg-yq
          - params:
              file: packaged/yq-*-x86_64.pkg.tar.zst.sig
            put: pacman-pkg-yq-sig
          - do:
              - config:
                  inputs:
                    - name: packaged
                    - name: version
                    - name: index
                  outputs:
                    - name: index
                  params:
                    GPG_KEY_ID: ((gpg.key-id))
                    GPG_PRIVATE_KEY: ((gpg.private-key))
                  platform: linux
                  run:
                    args:
                      - -exc
                      - /gpg-init.sh repo-add --verify --sign -n index/mdicsme.db.tar.gz packaged/yq-$(cat version/version)-1-x86_64.pkg.tar.zst
                    path: sh
                image: devinchristianson-fpm_archlinux-latest
                task: rebuild-index-for-pacman-yq
              - get_params:
                  options:
                    - --exclude '*'
                    - --include 'mdicsme.db'
                    - --include 'mdicsme.files'
                    - --include 'mdicsme.*.tar.gz'
                    - --include 'mdicsme.*.tar.gz.sig'
                  prefix: pacman
                  source_dir: index
                params:
                  options:
                    - --exclude '*'
                    - --include 'mdicsme.db'
                    - --include 'mdicsme.files'
                    - --include 'mdicsme.*.tar.gz'
                    - --include 'mdicsme.*.tar.gz.sig'
                  prefix: pacman
                  source_dir: index
                put: index
    serial_groups:
      - pacman
  - name: package-rpm-yq
    plan:
      - in_parallel:
          - get: yq-release
            params:
              globs:
                - yq_linux_amd64
            trigger: true
          - get: index
            params:
              options:
                - --exclude '*'
                - --include 'repodata/*'
                - --include 'cache/*'
              prefix: rpm
          - get: devinchristianson-fpm_fedora-37
      - config:
          image_resource:
            name: alpine
            source:
              repository: alpine
            type: registry-image
          inputs:
            - name: yq-release
          outputs:
            - name: version
          platform: linux
          run:
            args:
              - -exc
              - echo $(cat yq-release/tag) > version/version
            path: sh
        task: save-version
      - config:
          inputs:
            - name: yq-release
            - name: version
          outputs:
            - name: packaged
          platform: linux
          run:
            args:
              - -exc
              - fpm -t rpm -s dir --name yq --version $(cat version/version) --architecture native --description 'yq is a portable command-line YAML, JSON, XML, CSV and properties processor' --license 'Apache 2.0' --url 'https://github.com/mikefarah/yq' --vendor 'Built by github.com/devinchristianson/simple-packaging' -p packaged/ yq-release/yq_linux_amd64=/usr/bin/yq
            path: sh
        image: devinchristianson-fpm_fedora-37
        task: package-rpm-yq
      - config:
          inputs:
            - name: packaged
            - name: version
          outputs:
            - name: packaged
          params:
            GPG_KEY_ID: ((gpg.key-id))
            GPG_PRIVATE_KEY: ((gpg.private-key))
          platform: linux
          run:
            args:
              - -exc
              - /gpg-init.sh rpm --addsign packaged/yq-$(cat version/version)-1.x86_64.rpm
            path: sh
        image: devinchristianson-fpm_fedora-37
        task: sign-rpm-yq
      - in_parallel:
          - params:
              file: packaged/yq-*.x86_64.rpm
            put: rpm-pkg-yq
          - do:
              - config:
                  inputs:
                    - name: packaged
                    - name: version
                    - name: index
                  outputs:
                    - name: index
                  platform: linux
                  run:
                    args:
                      - --update
                      - --cachedir
                      - cache
                      - -o
                      - index
                      - packaged
                    path: createrepo
                image: devinchristianson-fpm_fedora-37
                task: rebuild-index-for-rpm-yq
              - config:
                  inputs:
                    - name: packaged
                    - name: version
                    - name: index
                  outputs:
                    - name: index
                  params:
                    GPG_KEY_ID: ((gpg.key-id))
                    GPG_PRIVATE_KEY: ((gpg.private-key))
                  platform: linux
                  run:
                    args:
                      - gpg
                      - --yes
                      - --detach-sign
                      - --armor
                      - index/repodata/repomd.xml
                    path: /gpg-init.sh
                image: devinchristianson-fpm_fedora-37
                task: resign-index-for-rpm-yq
              - get_params:
                  options:
                    - --exclude '*'
                    - --include 'repodata/*'
                    - --include 'cache/*'
                  prefix: rpm
                  source_dir: index
                params:
                  options:
                    - --exclude '*'
                    - --include 'repodata/*'
                    - --include 'cache/*'
                  prefix: rpm
                  source_dir: index
                put: index
    serial_groups:
      - rpm
resource_types:
  - name: simple-s3
    source:
      repository: troykinsella/s3-resource-simple
    type: docker-image
resources:
  - name: index
    source:
      access_key_id: ((s3-mdics-repo.access-key))
      aws_options:
        - --endpoint-url https://s3.us-east-2.wasabisys.com/
      bucket: pkg.mdics.me
      secret_access_key: ((s3-mdics-repo.secret-key))
    type: simple-s3
  - name: pacman-pkg-hello-world
    source:
      access_key_id: ((s3-mdics-repo.access-key))
      bucket: pkg.mdics.me
      endpoint: s3.us-east-2.wasabisys.com
      regexp: pacman/hello-world-(.*)-x86_64.pkg.tar.zst
      secret_access_key: ((s3-mdics-repo.secret-key))
    type: s3
  - name: pacman-pkg-hello-world-sig
    source:
      access_key_id: ((s3-mdics-repo.access-key))
      bucket: pkg.mdics.me
      endpoint: s3.us-east-2.wasabisys.com
      regexp: pacman/hello-world-(.*)-x86_64.pkg.tar.zst.sig
      secret_access_key: ((s3-mdics-repo.secret-key))
    type: s3
  - name: rpm-pkg-hello-world
    source:
      access_key_id: ((s3-mdics-repo.access-key))
      bucket: pkg.mdics.me
      endpoint: s3.us-east-2.wasabisys.com
      regexp: rpm/hello-world-(.*).x86_64.rpm
      secret_access_key: ((s3-mdics-repo.secret-key))
    type: s3
  - name: pacman-pkg-yq
    source:
      access_key_id: ((s3-mdics-repo.access-key))
      bucket: pkg.mdics.me
      endpoint: s3.us-east-2.wasabisys.com
      regexp: pacman/yq-(.*)-x86_64.pkg.tar.zst
      secret_access_key: ((s3-mdics-repo.secret-key))
    type: s3
  - name: pacman-pkg-yq-sig
    source:
      access_key_id: ((s3-mdics-repo.access-key))
      bucket: pkg.mdics.me
      endpoint: s3.us-east-2.wasabisys.com
      regexp: pacman/yq-(.*)-x86_64.pkg.tar.zst.sig
      secret_access_key: ((s3-mdics-repo.secret-key))
    type: s3
  - name: rpm-pkg-yq
    source:
      access_key_id: ((s3-mdics-repo.access-key))
      bucket: pkg.mdics.me
      endpoint: s3.us-east-2.wasabisys.com
      regexp: rpm/yq-(.*).x86_64.rpm
      secret_access_key: ((s3-mdics-repo.secret-key))
    type: s3
  - name: simple-packaging
    source:
      branch: main
      paths:
        - packages/hello-world/*
      private_key: ((github.private_key))
      uri: https://github.com/devinchristianson/simple-packaging.git
    type: git
  - name: yq-release
    source:
      access_token: ((github.access_key))
      owner: mikefarah
      repository: yq
    type: github-release
  - name: devinchristianson-fpm_archlinux-latest
    source:
      repository: devinchristianson/fpm
      tag: archlinux-latest
    type: registry-image
  - name: devinchristianson-fpm_fedora-37
    source:
      repository: devinchristianson/fpm
      tag: fedora-37
    type: registry-image
